# Generated by Django 5.0 on 2024-04-26 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_feedback'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Feedback',
        ),
    ]
